trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: AzureCLI@2
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        azureSubscription: 'PersonalProjectsSC'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript:  |
          terraform --version
          terraform init
          terraform plan --var-file prod.tfvars -out=$(System.DefaultWorkingDirectory)/tfplan
      displayName: 'Terraform Init and Plan'
    
    - publish: $(System.DefaultWorkingDirectory)/tfplan
      artifact: tfplan
      displayName: 'Publish tfplan artifact'


- stage: Deploy
  displayName: 'Terraform Apply'
  trigger: manual
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - download: current
      artifact: tfplan
      displayName: 'Download tfplan artifact'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'PersonalProjectsSC'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        inlineScript: |
          terraform --version
          terraform init
          terraform apply --var-file prod.tfvars -auto-approve $(Pipeline.Workspace)/tfplan/tfplan
      displayName: 'Terraform Init and Apply'
